# Generated by Django 6.0.6 on 2026-06-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_hp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pesanan', models.CharField(max_length=50, unique=True)),
                ('nama_produk', models.CharField(max_length=200)),
                ('jumlah', models.PositiveIntegerField()),
                ('harga_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_pesanan', models.DateField()),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retur.pembeli')),
            ],
        ),
        migrations.CreateModel(
            name='ReturBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alasan_retur', models.TextField()),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diproses', 'Diproses'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('tanggal_retur', models.DateField(auto_now_add=True)),
                ('foto_bukti', models.ImageField(blank=True, null=True, upload_to='bukti_retur/')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retur.pesanan')),
            ],
        ),
        migrations.CreateModel(
            name='PengembalianDana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_dana', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metode_pengembalian', models.CharField(choices=[('transfer_bank', 'Transfer Bank'), ('dompet_digital', 'Dompet Digital'), ('saldo_shopee', 'Saldo Shopee')], max_length=30)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('gagal', 'Gagal')], default='menunggu', max_length=20)),
                ('tanggal_proses', models.DateField(auto_now_add=True)),
                ('no_rekening', models.CharField(blank=True, max_length=50, null=True)),
                ('retur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='retur.returbarang')),
            ],
        ),
    ]
